package com.exodus.weather.store;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FUTURE_WEATHER".
*/
public class FutureWeatherDao extends AbstractDao<FutureWeather, Long> {

    public static final String TABLENAME = "FUTURE_WEATHER";

    /**
     * Properties of entity FutureWeather.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Weather_icon = new Property(1, Integer.class, "weather_icon", false, "WEATHER_ICON");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property Temp = new Property(3, Integer.class, "temp", false, "TEMP");
        public final static Property City_id = new Property(4, Long.class, "city_id", false, "CITY_ID");
    }

    private DaoSession daoSession;

    private Query<FutureWeather> city_FutureWeatherQuery;

    public FutureWeatherDao(DaoConfig config) {
        super(config);
    }
    
    public FutureWeatherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FUTURE_WEATHER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"WEATHER_ICON\" INTEGER," + // 1: weather_icon
                "\"DATE\" INTEGER," + // 2: date
                "\"TEMP\" INTEGER," + // 3: temp
                "\"CITY_ID\" INTEGER);"); // 4: city_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FUTURE_WEATHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FutureWeather entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer weather_icon = entity.getWeather_icon();
        if (weather_icon != null) {
            stmt.bindLong(2, weather_icon);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
 
        Integer temp = entity.getTemp();
        if (temp != null) {
            stmt.bindLong(4, temp);
        }
 
        Long city_id = entity.getCity_id();
        if (city_id != null) {
            stmt.bindLong(5, city_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FutureWeather entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer weather_icon = entity.getWeather_icon();
        if (weather_icon != null) {
            stmt.bindLong(2, weather_icon);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
 
        Integer temp = entity.getTemp();
        if (temp != null) {
            stmt.bindLong(4, temp);
        }
 
        Long city_id = entity.getCity_id();
        if (city_id != null) {
            stmt.bindLong(5, city_id);
        }
    }

    @Override
    protected final void attachEntity(FutureWeather entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FutureWeather readEntity(Cursor cursor, int offset) {
        FutureWeather entity = new FutureWeather( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // weather_icon
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // date
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // temp
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // city_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FutureWeather entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWeather_icon(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setTemp(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setCity_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FutureWeather entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FutureWeather entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FutureWeather entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "FutureWeather" to-many relationship of City. */
    public List<FutureWeather> _queryCity_FutureWeather(Long city_id) {
        synchronized (this) {
            if (city_FutureWeatherQuery == null) {
                QueryBuilder<FutureWeather> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.City_id.eq(null));
                city_FutureWeatherQuery = queryBuilder.build();
            }
        }
        Query<FutureWeather> query = city_FutureWeatherQuery.forCurrentThread();
        query.setParameter(0, city_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCityDao().getAllColumns());
            builder.append(" FROM FUTURE_WEATHER T");
            builder.append(" LEFT JOIN CITY T0 ON T.\"CITY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FutureWeather loadCurrentDeep(Cursor cursor, boolean lock) {
        FutureWeather entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        City city = loadCurrentOther(daoSession.getCityDao(), cursor, offset);
        entity.setCity(city);

        return entity;    
    }

    public FutureWeather loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FutureWeather> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FutureWeather> list = new ArrayList<FutureWeather>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FutureWeather> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FutureWeather> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
